### PR TITLE
Add english Syntax chapter

### PR DESCRIPTION
**Pull request by Hoverbear**
Contributes to #28 .

### CODE REVIEW

**Comment by skade** [comment]
I would put "if let" after match.

**Comment by Hoverbear** [comment]
@skade Would you suggest putting `if` and `if let` after, or giving `if let` it's own (third) slide?

**Comment by skade** [comment]
I would give if let a separate slide, as I consider it a special form of pattern matching.

**Comment by Hoverbear** [comment]
Our opinions differ, but I'll go with your preference!

**Pull request merged**
